# Generated by Django 3.1.4 on 2021-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='upload/')),
                ('status', models.IntegerField(choices=[('pending', 'PENDING'), ('draft', 'DRAFT'), ('published', 'PUBLISHED')])),
            ],
        ),
    ]
