# Generated by Django 3.1.4 on 2021-01-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vieclam24h', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vieclam24h.category')),
            ],
            bases=('vieclam24h.category',),
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='upload/')),
                ('status', models.IntegerField(choices=[('pending', 'PENDING'), ('draft', 'DRAFT'), ('published', 'PUBLISHED')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation', to='vieclam24h.category')),
            ],
        ),
        migrations.CreateModel(
            name='AdminOccupation',
            fields=[
                ('occupation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vieclam24h.occupation')),
            ],
            bases=('vieclam24h.occupation',),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='upload/')),
                ('status', models.IntegerField(choices=[('pending', 'PENDING'), ('draft', 'DRAFT'), ('published', 'PUBLISHED')])),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation', to='vieclam24h.occupation')),
            ],
        ),
    ]
