# Generated by Django 3.1.4 on 2021-01-28 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vieclam24h', '0002_admincategory_adminoccupation_job_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vieclam24h.job')),
            ],
            bases=('vieclam24h.job',),
        ),
        migrations.CreateModel(
            name='JobCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('descriptions', models.TextField(null=True)),
                ('confirm_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('review_content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_collaborators', to='vieclam24h.job')),
            ],
        ),
    ]
