# Generated by Django 3.1.4 on 2021-02-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminRealestateCategory',
        ),
    ]
