# Generated by Django 3.1.4 on 2021-02-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210212_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_type', to='blog.category'),
        ),
    ]
